# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(n, t0, t1, lam, a, mu, b) {
    .Call('_HErlangSRM_test', PACKAGE = 'HErlangSRM', n, t0, t1, lam, a, mu, b)
}

