# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cherlang_emest <- function(t, i, j, n, omega, p_, lam_, a, mu_, b, gn = 15L, geps = 1.0e-8, atol = 1.0e-3, rtol = 1.0e-6, maxiter = 2000L) {
    .Call('_HErlangSRM_Cherlang_emest', PACKAGE = 'HErlangSRM', t, i, j, n, omega, p_, lam_, a, mu_, b, gn, geps, atol, rtol, maxiter)
}

Cherlang_mvfd <- function(t, model) {
    .Call('_HErlangSRM_Cherlang_mvfd', PACKAGE = 'HErlangSRM', t, model)
}

Cherlang_mvfc <- function(t, model, gn = 15L, geps = 1.0e-8) {
    .Call('_HErlangSRM_Cherlang_mvfc', PACKAGE = 'HErlangSRM', t, model, gn, geps)
}

Cherlang_reli <- function(t, s, model) {
    .Call('_HErlangSRM_Cherlang_reli', PACKAGE = 'HErlangSRM', t, s, model)
}

Cherlang_pc <- function(t, s, model, gn = 15L, geps = 1.0e-8) {
    .Call('_HErlangSRM_Cherlang_pc', PACKAGE = 'HErlangSRM', t, s, model, gn, geps)
}

Cherlang_relic <- function(t, s, model, gn = 15L, geps = 1.0e-8) {
    .Call('_HErlangSRM_Cherlang_relic', PACKAGE = 'HErlangSRM', t, s, model, gn, geps)
}

test_daxpy <- function(a, x, y) {
    .Call('_HErlangSRM_test_daxpy', PACKAGE = 'HErlangSRM', a, x, y)
}

test_dscal <- function(a, x) {
    .Call('_HErlangSRM_test_dscal', PACKAGE = 'HErlangSRM', a, x)
}

test_dasum <- function(x) {
    .Call('_HErlangSRM_test_dasum', PACKAGE = 'HErlangSRM', x)
}

test_dgemv <- function(trans, a, A, x, b, y) {
    .Call('_HErlangSRM_test_dgemv', PACKAGE = 'HErlangSRM', trans, a, A, x, b, y)
}

test_dgemm <- function(transA, transB, a, A, B, b, C) {
    .Call('_HErlangSRM_test_dgemm', PACKAGE = 'HErlangSRM', transA, transB, a, A, B, b, C)
}

test_mexp_unif <- function(trans, P, qv, t, x) {
    .Call('_HErlangSRM_test_mexp_unif', PACKAGE = 'HErlangSRM', trans, P, qv, t, x)
}

