# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cemest <- function(t, i, j, n, omega, p_, lam_, a, mu_, b, gn = 15L, geps = 1.0e-8, atol = 1.0e-3, rtol = 1.0e-6, maxiter = 2000L) {
    .Call('_HErlangSRM_Cemest', PACKAGE = 'HErlangSRM', t, i, j, n, omega, p_, lam_, a, mu_, b, gn, geps, atol, rtol, maxiter)
}

Cmvfd <- function(t, model) {
    .Call('_HErlangSRM_Cmvfd', PACKAGE = 'HErlangSRM', t, model)
}

Cmvfc <- function(t, model, gn = 15L, geps = 1.0e-8) {
    .Call('_HErlangSRM_Cmvfc', PACKAGE = 'HErlangSRM', t, model, gn, geps)
}

